{% set name = "langchainhub" %}
{% set version = "0.1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchainhub-{{ version }}.tar.gz
  sha256: af7df0cb1cebc7a6e0864e8632ae48ecad39ed96568f699c78657b9d04e50b46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - requests >=2.0.0,<3.0.0
    - types-requests >=2.31.0,<3.0.0
    - typing-extensions

test:
  imports:
    - langchainhub
  commands:
    - pip check
  requires:
    - pip

about:
  summary: The LangChain Hub API client
  home: https://github.com/hwchase17/langchain-hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
